services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gigit
    ports:
      - "5432:5432"
    volumes:
      - gigit_pgdata:/var/lib/postgresql/data

volumes:
  gigit_pgdata:

